# Generated by Django 5.2.4 on 2025-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("register", "Register"),
                            ("attendance_marked", "Attendance Marked"),
                            ("student_added", "Student Added"),
                            ("course_added", "Course Added"),
                            ("user_approved", "User Approved"),
                            ("user_denied", "User Denied"),
                            ("password_changed", "Password Changed"),
                            ("email_verified", "Email Verified"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(help_text="Activity description")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional activity data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities_activity",
                "ordering": ["-created_at"],
            },
        ),
    ]
