# Generated by Django 5.2.4 on 2025-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Student name", max_length=255)),
                (
                    "regNo",
                    models.CharField(
                        help_text="Registration number", max_length=50, unique=True
                    ),
                ),
                ("level", models.CharField(help_text="Academic level", max_length=20)),
                ("fingerPrint", models.TextField(help_text="Fingerprint data")),
                (
                    "addmissionYear",
                    models.CharField(help_text="Admission year", max_length=10),
                ),
                ("email", models.EmailField(help_text="Student email", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ManyToManyField(
                        help_text="Enrolled courses",
                        related_name="students",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "students_student",
                "ordering": ["regNo"],
            },
        ),
    ]
