# Generated by Django 5.2.4 on 2025-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courseTitle",
                    models.CharField(help_text="Course title", max_length=255),
                ),
                (
                    "courseCode",
                    models.CharField(
                        help_text="Course code", max_length=20, unique=True
                    ),
                ),
                ("semester", models.CharField(help_text="Semester", max_length=20)),
                ("level", models.CharField(help_text="Academic level", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses_course",
                "ordering": ["courseCode"],
            },
        ),
    ]
