# Generated by Django 5.2.4 on 2025-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Session name", max_length=255)),
                ("start", models.DateField(help_text="Session start date")),
                ("end", models.DateField(help_text="Session end date")),
                (
                    "semesters",
                    models.JSONField(default=list, help_text="List of semesters"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Is this session active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "db_table": "academic_sessions_academicsession",
                "ordering": ["-start"],
            },
        ),
    ]
